NodeOUs:
    Enable: true
    ClientOUIdentifier:
        Certificate: cacerts/kky-dell-7057.pem
        OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
        Certificate: cacerts/kky-dell-7057.pem
        OrganizationalUnitIdentifier: peer
    AdminOUIdentifier:
        Certificate: cacerts/kky-dell-7057.pem
        OrganizationalUnitIdentifier: admin
    OrdererOUIdentifier:
        Certificate: cacerts/kky-dell-7057.pem
        OrganizationalUnitIdentifier: orderer